spring.application.name=api
jwt.secret=${JWT-SECRET}
jwt.expiration=86400000
spring.jpa.hibernate.ddl-auto=create-drop
spring.sql.init.mode=always
spring.datasource.driverClassName=org.postgresql.Driver
## nome del database
spring.datasource.url=jdbc:postgresql://postgres:5432/cityvoice
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.jackson.mapper.accept-case-insensitive-enums=true